version: "3.7"
  
services:
  
  database:
    container_name: database
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=P123456p
      - MYSQL_DATABASE=bookstore_db
      - MYSQL_USER=clarusway
      - MYSQL_PASSWORD=Clarusway_1
    networks:
      - balabannet
    restart: always    
  
  server:
    image: balaban/bookstoreapi
    depends_on:
      - database
    ports:
      - "80:80" 
    networks:
      - balabannet
    restart: always
    container_name: server
    labels:
      kompose.service.type: "nodeport"
      kompose.service.nodeport.port: "30001"
      kompose.service.expose: "www.deryabalaban.online"         

networks:
  balabannet:
    driver: bridge
